Adding Car Class
CSC207-UofT/lab-3-trader-tut5101-identifier pull request #2
Opened 2021-09-27 23:54 UTC by johnwon2007

2021-09-27 23:58 UTC, Polymatth requested changes
Everything looks good!

2021-09-27 23:58 UTC, Polymatth commented on src/test/java/CarTest.java
> +        assertEquals(20, c.getMaxSpeed());
Error assertEquals False please fix :)

2021-09-27 23:59 UTC, kdr47 reviewed
error in cartest.java line 27

2021-09-28 00:02 UTC, Polymatth approved these changes
Everything looks great

2021-09-28 00:03 UTC, merged